### PR TITLE
feat(core): add Service execution concepts

### PR DESCRIPTION
**Pull request by ccamel**
## Purpose

This PR introduces the concepts related to the execution of services as required by #98.

### `ServiceExecutionOrder`

Added the `ServiceExecutionOrder` class, which provides a formal representation of the order of the services that should be executed. To specify the details of a service execution, such as the required resources (datasets), expected results, and potential time considerations, `metadata` should be used.

The `ServiceExecutionOrder` class is defined using the following restrictions:

- `hasContractingParty`: relationship between a Service Execution Order and the contracting party (aka Client) who initiates the _contract_.
- `hasContractor`: represents the relationship between a Service Execution Order and the contractor (aka Service Provider, typically the workflow engine) responsible for executing the terms and conditions of the contract as agreed upon with the contracting party.
- `hasObject`: specifies the service which is the object of the execution.

```
Class: 'Service Execution Order'
   EquivalentTo: 
        ('has contracting party' only 'Decentralized Identifier URI')
         and ('has contractor' only Service)
         and ('has object' only Service)
```

### `ServiceExecution`

Added the `Service Execution` class, which represents the execution of a service in a workflow with specific inputs and outputs.

The ServiceExecution class is defined using the following restrictions:

- `hasObject`: a property that expresses the relationship between a service execution and the object of the execution, i.e. the service executed.
- `produces`: a property that specifies the output of a service execution, which could be metadata or datasets.
- `hasInput`: a property that specifies the input datasets required for a service execution.
- `specifiedBy`: a property that references the `ServiceExecutionOrder` that describes the service execution order in which this service execution belongs.
- `hasParent`: a property that specifies the parent service execution that this service execution belongs to, if any. This property allows to define a directed acyclic graph (DAG) of service executions, where each service execution is a node in the graph and the `hasParent` property defines the edges between nodes.

```
Class: 'Service Execution'
    EquivalentTo: 
        ((produces only Dataset) or (produces only Metadata))
         and ('has input' only Dataset)
         and ('has object' only Service)
         and ('has parent' only 'Service Execution')
         and ('specified by' only 'Service Execution Order')
```

## Overview

The following diagram depicts the introduced concepts and their relationship with the already existing concepts of the ontology.

```mermaid
classDiagram
    Dataset --> Service : providedBy

    class Metadata{
      <<abstract>>
    }
    Metadata <|.. ServiceGeneralMetadata
    Metadata <|.. DatasetGeneralMetadata
    Metadata <|.. ServiceExecutionMetadata
    Metadata <|.. ServiceSpecificationMetadata

    ServiceExecutionMetadata ..> ServiceExecution : describes

    ServiceGeneralMetadata ..> Service : describes
    ServiceSpecificationMetadata ..> Service : describes
    DatasetGeneralMetadata ..> Dataset : describes

    ServiceExecutionOrder --> Service : hasObject
    ServiceExecutionOrder --> Service : has contractor

    ServiceExecution --> ServiceExecutionOrder : specifiedBy

    ServiceExecution --> Service : hasObject
    ServiceExecution --> ServiceExecution : hasParent

    ServiceExecution --> Dataset : hasInput
    ServiceExecution --> Dataset : produces
    ServiceExecution --> Metadata : produces
```

The following diagram shows the possible instances of Service Execution:

```mermaid
graph TD;
  subgraph data
    D1
    D2
    D3   
  end
  subgraph metadata
    M1
    M2
    M3
  end
  subgraph service
    SE1
    SE2
    SE3
    SE4
  end

  M1 -.describes.-> D1
  M2 -.describes.-> D1
  M3 -.describes.-> D1
  SE4 --hasParent--> SE3
  SE3 --hasParent--> SE2
  SE2 --hasParent--> SE1
  SE1 --hasInput--> D1
  SE2 --hasInput--> D1
  SE1 --produces--> M1
  SE2 --produces--> M2
  SE2 --produces--> M3
  SE3 --hasInput--> M1
  SE3 --hasInput--> M2
  SE3 --hasInput--> M3
  SE3 --hasInput--> D1
  SE3 --produces--> D2
  SE4 --hasInput--> D1
  SE4 --hasInput--> D2
  SE4 --produces--> D3
```

### CODE REVIEW

**Review by MdechampG — COMMENTED** [review]
Thank you @ccamel for this clear explanation ! 
I have just a doubt : for the example of the instances of ServiceExecution, does it follow 1 ServiceExecutionOrder for all the tree or 1 ServiceExecutionOrder by node ?

**Comment by ccamel** [comment]
@MdechampG There's only one `ServiceExecutionOrder` for a service workflow to trigger. And then, for each service invoked by the workflow engine (including the workflow service itself), a `ServiceExecution` is created. So regarding the tree of execution for a workflow, we have: 1 `ServiceExecutionOrder` for all the tree, and n `ServiceExecution` by node (service) ?

**Review by amimart — APPROVED** [review]
Great, from what I see there's nothing missing or incoherent. 👍

**Comment by ccamel** [comment]
Thanks to everyone who reviewed. Let's merge this now. If any problems come up later, we can address them. :relieved:

**Pull request merged**
