### PR TITLE
Refactor/dataspace

### PR DESCRIPTION
**Pull request by ccamel**
## Purpose

Redefines the concept of Data Space, the related concepts and the relationships that link them.

### Before

image

### After

image

### Citizen

The concept `Citizen` is removed, as it is too dogmatic and connoted in the context in which it is used. This concept is replaced by the concept `Resource`.

### Resource

We introduce the concept of `Resource` (in replacement of the concept `Citizen`) which represents all the kinds of members of a `DataSpace`. It specifies the large family of individuals belonging to a dataspace, whether they are a dataset, a service or anything else. The class is defined as the union set of all its members, which for now is reduced to a single kind: datasets.

Moreover, to be considered as a `Resource`, an instance must have the `belongsTo` property pointing to a `DataSpace` instance.

**Definition:**

> A `Resource` is equivalent to `Dataset` (and a reciprocally a `Dataset` is a `Resource`)

```
    EquivalentTo: 
        Dataset
    
    SubClassOf: 
        belongsTo only DataSpace
```

### DataSpace

We amend the `DataSpace` definition to:
- remove the axiom that states that a citizen's membership in his dataspace.
- add the subclassing from a `Data`. Indeed, a data space is also a data in the sense that it can be described by a metadata.
- remove the property `:isNamed` and `:isDescribedBy` which become irrelevant if the Datas Space is described by metadata. These properties will be attached to a particular profile - to be defined.

**Definition**

```
    SubClassOf: 
        Data
```

## Example

Last but not least, let's create some individual instances of the classes newly introduced.

```turtle
@prefix : <https://ontology.okp4.com/world/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix foo: <http://foo> .
@prefix ns0: <http://ns.exiftool.org/1.0/> .
@prefix ns1: <http://ns.exiftool.org/ExifTool/1.0/> .
@prefix ns2: <http://ns.exiftool.org/File/System/1.0/> .
@prefix ns3: <http://ns.exiftool.org/File/1.0/> .

# A dataspace (and its metadata)

<https://ontology.okp4.com/world/78a3f817-9cf6-4b6e-89b1-ddde80595e97> 
  a owl:NamedIndividual, :DataSpace .
                                         
# A metadata describing the dataspace

<https://ontology.okp4.com/world/2e5509d6-8842-4b67-8dba-46c43fe09823>
  rdf:type owl:NamedIndividual, :Metadata ;
  foo:description "My beautiful dataspace" ;
  :describes <https://ontology.okp4.com/world/78a3f817-9cf6-4b6e-89b1-ddde80595e97> .

# A dataset                                                                             

<https://ontology.okp4.com/world/5d792b01-6e7a-4837-80ad-a8516c184bae>
  a owl:NamedIndividual, :Dataset ;
  :belongsTo <https://ontology.okp4.com/world/78a3f817-9cf6-4b6e-89b1-ddde80595e97> .

# A metadata (exiftool profile) describing the dataset

<https://ontology.okp4.com/world/0cc88f43-849a-41ce-bdee-0ba45907f456>
  rdf:type owl:NamedIndividual, :Metadata ;
  ns2:FileName "hw_25000.csv" ;
  ns2:FileSize "619 KiB" ;
  ns2:FileModifyDate "2021:09:24 20:29:15+02:00" ;
  ns3:FileType "CSV" ;
  ns3:FileTypeExtension "csv" ;
  ns3:MIMEType "text/csv" ;
  ns3:MIMEEncoding "us-ascii" ;
  :describes <https://ontology.okp4.com/world/5d792b01-6e7a-4837-80ad-a8516c184bae> .

# Another metadata (specific profile for csv files) describing the same dataset

<https://ontology.okp4.com/world/0cc88f43-849a-41ce-bdee-0ba45907f457>
  a owl:NamedIndividual, :Metadata ;
  foo:Newlines "Unix LF" ;
  foo:Delimiter "Comma" ;
  foo:Quoting "Double quotes" ;
  foo:ColumnCount "3" ;  
  foo:RowCount "247" ;
  :describes <https://ontology.okp4.com/world/5d792b01-6e7a-4837-80ad-a8516c184bae> .
```

### CODE REVIEW

**Review by henigh — COMMENTED** [review]
I have some questions.
Is the concept of `service` missing here ?
Do we need to attach `gouvernance` / `rulebook` as a `dataspace` property / class ?
If ressource = dataset, why do we have both ?
Do we have an explicit definition of `data` and `dataset` ?
Is `data` a subclass of `dataspace` ? (do I understand correctly..?)
Thnx ^^

**Comment by MdechampG** [comment]
> 

@henigh 

- This work is still in progress so the concept 'service' is not yet defined (there is a dedicated issue)
- A Resource is equivalent to Dataset (and a reciprocally a Dataset is a Resource). We do have these 2 concepts because a service will be a resource as well. So I guess we will have : A resource is equivalent to Dataset OR Service. And a Service is a Resource. 
- It is the contrary : `dataspace` is a subclass of `data`
- As for the definition of data and dataset : I don't know 
- As for the governance, I wonder the same. @ccamel the governance rules will be metadata of the dataspace or properties ?

**Review by MdechampG — APPROVED** [review]

**Review by ad2ien — APPROVED** [review]

**Review by fredericvilcot — APPROVED** [review]

**Comment by henigh** [comment]
> * This work is still in progress so the concept 'service' is not yet defined (there is a dedicated issue)
> * A Resource is equivalent to Dataset (and a reciprocally a Dataset is a Resource). We do have these 2 concepts because a service will be a resource as well. So I guess we will have : A resource is equivalent to Dataset OR Service. And a Service is a Resource.
> * It is the contrary : `dataspace` is a subclass of `data`
> * As for the definition of data and dataset : I don't know
> * As for the governance, I wonder the same. @ccamel the governance rules will be metadata of the dataspace or properties ?  

Thank you Marine.
In that case, considering that fact that a dataspace is defined by it's **data**, **services**, and **a rulebook**,
I still don't understand the relationship of `subclass` between dataspace and data.
Here an example of subclass used in [FOAF](http://xmlns.com/foaf/0.1/) Ontology👇   

image

Maybe I'm missing something, but I see it more like this: `Data` ---belong to ---> `Dataspace`

**Review by amimart — APPROVED** [review]

**Comment by ccamel** [comment]
> Thank you Marine. In that case, considering that fact that a dataspace is defined by it's **data**, **services**, and **a rulebook**, I still don't understand the relationship of `subclass` between dataspace and data. Here an example of subclass used in [FOAF](http://xmlns.com/foaf/0.1/) Ontologypoint_down
>
> Maybe I'm missing something, but I see it more like this: `Data` ---belong to ---> `Dataspace`

Okay, I'll take over the conversion, because we need to move forward quickly on this concern.

From what I understand, I think there's a confusion between the concept of `data` and `dataset` in the ontology. `data` and `metadata` are just a general and abstract concepts that express the link between something which "is described" and something else that "describes". Since we want a `dataspace` to be described by metadata, then from a logical point of view, that makes a `dataspace` a `data` (in more precise terms, the concept `dataspace` is subsumed by the concept `data`). And in the same way, as a `service` is described by its metadata, then it's a `data` in the ontological sense. It may seem a bit strange to do this but this makes it possible to describe the quality of the relationships between concepts in a uniform way.

**Comment by ccamel** [comment]
@henigh some further clarifications:

- as @MdechampG said, this work does not cover the concept of 'service'. I have a work in progress which I will submit to another PR very soon.
- the governance rules, which are currently intended to be (partially) expressed in prolog,  at the current stage of our thinking, will be referenced by a property. But this is subject to change.

**Review by henigh — APPROVED** [review]

**Pull request merged**
