### PR TITLE
Feat/governance description

### PR DESCRIPTION
**Pull request by MdechampG**
# Feat/governance description

- [X] I've read the last version of [CODE_OF_CONDUCT.md](https://github.com/okp4/.github/blob/main/CODE-OF-CONDUCT.md) and [CONTRIBUTING.md](https://github.com/okp4/.github/blob/main/CONTRIBUTING.md)

## Description

This PR aims to add the property "hasDescription" to the Governance Metadata.
It includes the property in the model but also in the example instances (CROP, DDP, CADS, DS4I, Appel Agri).

### CODE REVIEW

**Review by Gab-pm — APPROVED** [review]

**Review by ccamel — APPROVED** [review]
lgtm! thanks. :+1:

**Comment by MdechampG** [comment]
FYI @fredericvilcot @lolottetheclash it's this property "hasDescription" of a Governance Chapter which will be requested for the portal (card Governance on the page of a Zone). 

image

**Review by SonnevilleDamien — APPROVED** [review]

**Review by fredericvilcot — APPROVED** [review]
Great, thx @MdechampG 🙏

**Review by lolottetheclash — APPROVED** [review]
Thanks !

**Pull request merged**
