### PR TITLE
Build/split ontology

### PR DESCRIPTION
**Pull request by ccamel**
# Split the ontology into multiple files

## Description

As our ontology gets bigger and bigger, the need arises to be able to split it into several files. This PR proposes:
- to split the ontology into several files, each carrying an autonomous and consistent part of the ontology (each part can be edited in [protégé](https://protege.stanford.edu/) for instance),

```
src
├── category-service.ttl # a thesaurus
├── ontology.ttl  # the ontology
└── topic.ttl # a thesaurus
```

- to amend the `Makefile` to handle the merging of the parts into a single ontology (`okp4.ttl`), with preservation of:
  - the linting and doc generation tasks,
  - the release process

### Build process

The generation of the final ontology requires the invocation of the `build` target, which is now in the target directory.
To do this, it is necessary to serialize all the RDF parts from the [turtle](https://en.wikipedia.org/wiki/Turtle_(syntax)) syntax to the [N-Triples](https://en.wikipedia.org/wiki/N-Triples) format, concatenate it and serialize back from [N-Triples](https://en.wikipedia.org/wiki/N-Triples) format to the [turtle](https://en.wikipedia.org/wiki/Turtle_(syntax)) syntax.

```text
target
├── doc # the generated documentation
│   └── ontology
│       ├── images
│       ├── index-en.html
│       ├── ontology.jsonld
│       ├── ontology.nt
│       ├── ontology.rdf
│       ├── ontology.ttl
│       ├── provenance
│       ├── readme.md
│       ├── resources
│       └── webvowl
├── nt # the converted rdf file into N-Triples format
│   ├── category-service.nt
│   ├── ontology.nt
│   └── topic.nt
├── okp4.nt # the assembled ontology in N-Triples format
└── okp4.ttl # the assembled ontology in turtle format
```

### Dockerfile deletion

The Dockerfile has been removed. It is not so much useful in the context of the project, as the documentation is deployed through github pages, and not through a docker image. 

But the actual reason is, given the complexity of the build now performed by the `Makefile` - which uses docker under the hood - the build of the docker image would require docker in docker (dind) which is quite tricky (but if anyone wants to do it, I'd love to ☺️). 

## Testing

```sh
make build
make lint
make documentation

make clean
```

### CODE REVIEW

**Review by hleonardtek — APPROVED** [review]
Looks good !

**Review by ad2ien — COMMENTED** [review]
Hi, in the makefile, the `start-site` goal would need :
```
-v `pwd`/target/doc/ontology:/usr/local/apache2/htdocs/:ro \
```

instead of 

```
-v `pwd`/target/generated/ontology:/usr/local/apache2/htdocs/:ro \
```

**Comment by ccamel** [comment]
> Hi, in the makefile, the `start-site` goal would need :

Yes! Good catch! :+1: 
It's fixed. Thanks.

**Review by ad2ien — APPROVED** [review]
LGTM!

**Review by bdeneux — APPROVED** [review]

**Pull request merged**
